name: robustirc
description: A RobustIRC implementation in Dart
version: 0.1.0-alpha.2
homepage: https://github.com/Ampless/robustirc.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
