name: robustirc
description: An implementation of a RobustSession/RobustIRC client in Dart
version: 0.1.1
homepage: https://github.com/Ampless/robustirc.dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
